In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
import pandas as pd

path = "/data/mlproject22" if os.path.exists("/data/mlproject22") else "."
df = pd.read_csv(os.path.join(path, "transactions.csv.zip"))

df.head()

,Time,Feature0,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,...,Feature20,Feature21,Feature22,Feature23,Feature24,Feature25,Feature26,Feature27,Amount,Class
0,12187.0,1.127257,0.170387,1.675702,1.662017,-1.093046,-0.447651,-0.590031,-0.071291,2.015259,...,-0.170890,0.009832,0.066699,0.877103,0.350030,-0.482569,0.052777,0.038219,4.99,0
1,149717.0,-0.723098,-1.307087,1.119492,-2.486829,-1.781857,0.382495,0.221389,-0.021550,-1.964369,...,-0.457047,-0.980797,0.006519,-0.488353,0.336841,-0.335149,-0.027314,-0.226558,299.00,0
2,72288.0,1.357358,-0.802677,1.135552,-0.490788,-1.672022,-0.509976,-1.192288,0.044009,-0.001600,...,0.299976,0.911314,-0.096112,0.427782,0.436567,-0.044389,0.045821,0.024275,10.00,0
3,168435.0,1.891806,-0.123111,-1.791275,0.342303,0.235308,-0.723866,0.082800,-0.114664,0.767009,...,-0.186402,-0.408728,0.091938,-0.518938,-0.082267,-0.088265,-0.015244,-0.022998,61.19,0
4,55416.0,-0.378806,0.449422,0.154983,-0.899310,-0.678177,-1.419243,0.130648,0.087002,0.509679,...,0.053215,0.266919,0.514422,0.412200,-1.279881,-0.166479,0.071403,0.150137,27.75,0

In [3]:
df.shape

(227845, 31)

In [4]:
df["Class"].value_counts()

0    227451
1       394
Name: Class, dtype: int64

In [5]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    class_weight='balanced',
    max_iter=1000,
    random_state=42
)

lr.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [9]:
y_prob = lr.predict_proba(X_test)[:,1]

In [10]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 0.9776968647998865

In [11]:
from sklearn.metrics import classification_report

y_pred = lr.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99     45490
           1       0.05      0.94      0.10        79

    accuracy                           0.97     45569
   macro avg       0.53      0.95      0.54     45569
weighted avg       1.00      0.97      0.98     45569

In [12]:
y_prob[10]

0.06558725350981996

In [13]:
y_prob[85]

0.04358294990427005

In [14]:
import numpy as np

idx = np.argmax(y_prob)

print("Transaction:", idx)
print("Probability:", y_prob[idx])

Transaction: 485
Probability: 1.0

In [15]:
y_prob[485]

1.0

In [16]:
y_test.iloc[idx]

1

In [17]:
import numpy as np

idx = np.argmax(y_prob)

print("Transaction:", idx)
print("Probability:", y_prob[idx])

Transaction: 485
Probability: 1.0

In [18]:
y_prob[74]

9.114210343052647e-06

In [19]:
import numpy as np

high_risk = np.where(y_prob > 0.90)[0]

high_risk

array([  169,   190,   314,   485,   589,  1165,  1249,  1253,  1314,
        1723,  1927,  2110,  2265,  2427,  2689,  2851,  2925,  2966,
        2982,  3134,  3440,  3555,  3578,  3887,  3963,  4045,  4076,
        4253,  4280,  4397,  4578,  4707,  4724,  4750,  4840,  4885,
        4897,  4914,  5149,  5497,  5553,  5870,  5950,  6052,  6131,
        6248,  6412,  6418,  6498,  6673,  6771,  7365,  7512,  7710,
        8512,  8709,  8718,  8788,  8879,  9238,  9295,  9321,  9384,
        9421,  9476,  9628,  9720,  9836,  9998, 10007, 10128, 10289,
       10333, 10361, 11062, 11263, 11465, 11652, 11718, 11855, 11997,
       12034, 12046, 12376, 12387, 12391, 12591, 12623, 12765, 12816,
       13526, 13576, 13600, 13601, 13627, 14026, 14217, 14296, 14312,
       14402, 14446, 14553, 14886, 14897, 15145, 15162, 15221, 15306,
       15337, 15680, 16029, 16067, 16158, 16313, 16473, 16487, 16554,
       16719, 16959, 17339, 17380, 17549, 17686, 17716, 17750, 17930,
       18138, 18227, 18237, 18404, 18694, 18707, 18913, 18918, 18936,
       18940, 19045, 19057, 19227, 19685, 19778, 20236, 20431, 20457,
       20539, 20569, 20602, 20968, 21011, 21319, 21698, 21923, 22284,
       22537, 22848, 22888, 23016, 23085, 23420, 23525, 23895, 24105,
       24277, 24441, 24458, 24810, 24893, 25075, 25079, 25148, 25370,
       25432, 25829, 25991, 26014, 26090, 26150, 26163, 26627, 26894,
       27217, 27271, 27424, 28125, 28269, 28286, 28472, 28509, 28855,
       28962, 29045, 29196, 29613, 29752, 29838, 30547, 30956, 31525,
       32014, 32215, 32349, 32424, 32437, 32649, 32754, 33002, 33212,
       33224, 33307, 33378, 33391, 33638, 33951, 34035, 34098, 34440,
       34486, 34518, 34862, 34921, 35108, 35136, 35247, 35291, 36061,
       36131, 36401, 36603, 37091, 37255, 37535, 37742, 37747, 38046,
       38080, 38212, 38231, 38275, 38665, 38754, 38846, 38876, 39086,
       39195, 39978, 40357, 40478, 40802, 40956, 41151, 41386, 41595,
       41851, 42013, 42363, 42517, 42791, 42833, 42992, 43217, 43869,
       43904, 44027, 44057, 44073, 44130, 44439, 44544, 45037, 45078,
       45282, 45519, 45528])

In [20]:
y_prob[high_risk]

array([0.95079027, 0.98689507, 0.99966535, 1.        , 0.93215106,
       1.        , 1.        , 0.92844178, 0.97234215, 0.96567966,
       1.        , 0.98397422, 0.95071031, 0.91098   , 0.99893637,
       0.93462658, 0.97831835, 0.96590085, 0.95763044, 1.        ,
       0.95866923, 1.        , 0.92092391, 1.        , 0.9990551 ,
       0.93395221, 0.99648251, 0.93716069, 0.92904768, 0.91436563,
       0.94355355, 1.        , 1.        , 0.98864687, 0.93831666,
       1.        , 1.        , 0.9006381 , 1.        , 0.96570171,
       0.95592507, 0.92941144, 0.99982291, 0.96436157, 0.90737178,
       1.        , 0.91932902, 0.92615846, 1.        , 0.96352671,
       1.        , 0.99846545, 0.91752639, 0.97421091, 1.        ,
       0.93618817, 1.        , 1.        , 0.99999998, 0.90957741,
       0.93228932, 1.        , 0.98825584, 0.94780471, 0.9868945 ,
       1.        , 0.97229425, 0.94807286, 0.99671546, 0.96979075,
       0.91081106, 0.94920155, 0.9836632 , 1.        , 1.        ,
       0.9180372 , 0.99837425, 1.        , 0.9971438 , 1.        ,
       0.90262902, 0.94131059, 1.        , 1.        , 0.98128573,
       0.96547546, 0.97977178, 0.91781584, 0.94041527, 0.93036053,
       0.90623957, 0.99929473, 0.9139144 , 0.99999932, 1.        ,
       0.99957959, 1.        , 0.97830798, 0.96440935, 0.93248823,
       1.        , 0.96041329, 1.        , 0.92411016, 0.92002581,
       0.95766153, 0.95340569, 0.99999991, 0.99990437, 0.97144699,
       0.99361955, 1.        , 1.        , 0.94024235, 0.90163989,
       1.        , 0.96349245, 1.        , 1.        , 1.        ,
       0.90124499, 0.99985127, 0.98260065, 0.92087532, 1.        ,
       0.96905657, 0.95811216, 0.92769009, 0.98149794, 0.94061532,
       1.        , 0.9074241 , 0.96388414, 0.94009842, 0.93211002,
       0.93967464, 0.95601662, 0.93014501, 0.99991581, 0.94883779,
       1.        , 0.93614535, 1.        , 0.97300215, 0.9080848 ,
       0.90585512, 0.91747919, 1.        , 0.9873582 , 1.        ,
       0.97300662, 0.97396146, 0.93820825, 1.        , 0.94363347,
       0.99555259, 0.9069823 , 1.        , 1.        , 0.90909216,
       1.        , 0.94143302, 0.99708456, 0.98039538, 0.96731931,
       0.92217796, 1.        , 0.93321654, 0.93682292, 0.91092614,
       1.        , 1.        , 0.97793624, 0.93315573, 0.95236975,
       1.        , 0.94076449, 0.98244701, 0.93512086, 1.        ,
       0.92812291, 0.91831957, 1.        , 0.99855654, 1.        ,
       0.91429264, 0.90070276, 0.9587971 , 0.95605367, 0.94479827,
       0.99999974, 0.9954096 , 0.95752182, 0.94205638, 0.99763262,
       0.98431666, 1.        , 0.9999999 , 0.93049897, 0.94290971,
       1.        , 0.99989274, 0.96218148, 0.99815526, 0.98006546,
       0.92363811, 0.92634992, 0.95182725, 0.95536349, 0.9592427 ,
       0.94186599, 1.        , 0.91285216, 1.        , 1.        ,
       1.        , 0.9149189 , 0.9180462 , 0.99998734, 0.94471963,
       0.91135087, 0.90733488, 0.91546389, 0.96927596, 0.94850859,
       1.        , 0.9734732 , 0.99023623, 1.        , 0.99999999,
       0.99999996, 0.92066959, 0.91274792, 0.99842944, 0.99989511,
       0.93039952, 0.91655293, 0.936758  , 1.        , 0.95751491,
       0.98522252, 0.99994228, 0.91358924, 1.        , 1.        ,
       0.93693813, 0.90512418, 0.95842673, 0.93218272, 0.91455701,
       0.90826421, 0.92294409, 0.99964332, 0.97379082, 0.93975989,
       0.9016026 , 0.990862  , 1.        , 0.91072113, 0.97178479,
       0.99984305, 0.9999811 , 0.95602845, 1.        , 0.94652881,
       0.91464048, 0.90056561, 0.97059769, 0.99989953, 0.91741142,
       0.99555259, 0.94442916, 0.91706582])

In [21]:
df[df["Class"] == 1]

,Time,Feature0,Feature1,Feature2,Feature3,Feature4,Feature5,Feature6,Feature7,Feature8,...,Feature20,Feature21,Feature22,Feature23,Feature24,Feature25,Feature26,Feature27,Amount,Class
98,110552.0,-2.450367,2.107729,-5.140663,1.411304,-1.690780,-0.736427,-3.657946,1.944906,-0.788388,...,0.800538,0.364617,0.233608,-0.282078,-0.320311,0.492920,0.359976,-0.115471,80.22,1
504,7672.0,0.702710,2.426433,-5.234513,4.416661,-2.170806,-2.667554,-3.878088,0.911337,-0.166199,...,0.551180,-0.009802,0.721698,0.473246,-1.959304,0.319476,0.600485,0.129305,1.00,1
1904,165981.0,-5.766879,-8.402154,0.056543,6.950983,9.880564,-5.773192,-5.748879,0.721743,-1.076274,...,0.880395,-0.130436,2.241471,0.665346,-1.890041,-0.120803,0.073269,0.583799,0.00,1
2053,155359.0,-1.067713,5.262312,-8.438567,7.316487,0.008254,-2.125936,-3.307036,1.869838,-4.522584,...,0.547790,-0.491960,0.055914,-1.145369,0.068951,0.535055,0.539263,0.124255,0.77,1
2065,8614.0,-2.169929,3.639654,-4.508498,2.730668,-2.122693,-2.341017,-4.235253,1.703538,-1.305279,...,0.645103,-0.503529,-0.000523,0.071696,0.092007,0.308498,0.552591,0.298954,1.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224505,28143.0,-27.143678,15.365804,-28.407424,6.370895,-20.087878,-4.666313,-18.709479,17.903574,-3.722279,...,1.796826,-1.960974,-0.902247,0.144011,2.024388,-0.204214,1.332153,0.385891,99.99,1
224781,87202.0,-0.419820,-1.155978,-2.092516,2.786750,0.736297,-0.167292,1.600027,-0.117427,-0.796954,...,0.480640,0.533517,1.284645,0.516131,-0.602941,-0.305024,-0.021363,0.129096,451.27,1
227278,75033.0,-0.430330,0.985633,0.645789,0.317131,0.616332,-1.347462,1.078234,-0.161518,-0.492856,...,-0.016378,-0.207609,-0.164119,0.255280,0.454798,-0.505032,-0.039456,-0.006358,30.14,1
227418,20332.0,-15.271362,8.326581,-22.338591,11.885313,-8.721334,-2.324307,-16.196419,0.512882,-6.333685,...,-2.356896,1.068019,1.085617,-1.039797,-0.182006,0.649921,2.149247,-1.406811,1.00,1
227605,12597.0,-2.589617,7.016714,-13.705407,10.343228,-2.954461,-3.055116,-9.301289,3.349573,-5.654212,...,1.887738,0.333998,0.287659,-1.186406,-0.690273,0.631704,1.934221,0.789687,1.00,1